url: https://wepalapepacampestre.com
enforce_ssl: wepalapepacampestre.com
name: Wepa la Pepa Campestre (name)($$$)
description: Página en Jekyll para pepa ($$$)
paginate: 10
baseurl: ''
plugins: [jekyll-paginate]