url: https://wepalapepacampestre.com
enforce_ssl: wepalapepacampestre.com
name: Wepa la Pepa Campestre 
description: Hotel y restaurante. Tabio, Cundinamarca. Un espacio aparte. Dormir, comer, descansar. ¿Qué buscas?
baseurl: ''
plugins: [jekyll-paginate]
include: [_redirects]